# Server settings
server:
  port: 8070
  address: localhost


# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://120.76.100.182:8066/realDB?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: test
    serverName: 120.76.100.182
    username: root
    password: tianqiyqyd2016
    cachePrepStmts: true
    prepStmtsSize: 250
    maximumPoolSize: 100
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    thymeleaf:
          mode: HTML5
          encoding: utf-8
          content-type: text/html
          cache: false
          prefix: /view/
    cache:
      ehcache:
        config: ehcache.xml
# MyBatis
mybatis:
    typeAliasesPackage: cn.darkshadow.**.domain
    mapperLocations: classpath:/mybatis/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis: DEBUG,
       org.springframework: DEBUG

#EHCACHE
ehcache:
      name: objectCache
      maxEntriesLocalHeap: 10000
      overflowToDisk: true
      eternal: false
      timeToLiveSeconds: 3600
      timeToIdleSeconds: 3600
